name = "HCModlist"
author = "Sinivis"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9add4669ae2deab5f472351bf688efc219fec6daf09d738f4c6471a1e82c875d"

[versions]
minecraft = "1.20.1"
neoforge = "47.1.106"
