name = "HCModlist"
author = "Sinivis"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "fe32425f2ceda3ca48cbc768e908331fdbe27b5e44c38ff0ae9fa4ca1df9f1ea"

[versions]
minecraft = "1.20.1"
neoforge = "47.1.106"
