name = "HCModlist"
author = "Sinivis"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ac908db6e35a3bbbeab06a05234cf60f5a96a8ce65fc3916e6b7472a67c2ff32"

[versions]
minecraft = "1.20.1"
neoforge = "47.1.106"
