name = "HCModlist"
author = "Sinivis"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1baab9424ce409f733cdc1b4b370955ba0c2f0029fcd33056b16c1bc0f773268"

[versions]
minecraft = "1.20.1"
neoforge = "47.1.106"
