name = "HCModlist"
author = "Sinivis"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "df92520095b9ca9744dfd7eac963f3738d2c0d9af5b8598b0be4c69db841f893"

[versions]
minecraft = "1.20.1"
neoforge = "47.1.106"
